var answer1 = "EPISODIOS";
var answer2 = "SERVIDORES";
var cuerpo1 = "<td id='p'>";
var cuerpo2 = "</td>" + "<td id='d'>";
var cuerpo3 = "</a>" + " " + "-" + " ";
var cuerpo4 = "</a>" + "</td>" + "</tr>";

document.getElementById("descargas").innerHTML = 
"<table id='desc'>" + "<tr>" + "<th id='p'>" + answer1 + "</th>" + "<th id='d'>" + answer2 + "</th>" + "</tr>" + 
"<tr id='redesc' class='des1'>" + cuerpo1 + "01" + cuerpo2 + "<a target='_blank' href='" + des1_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des1_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des1_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des2'>" + cuerpo1 + "02" + cuerpo2 + "<a target='_blank' href='" + des2_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des2_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des2_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des3'>" + cuerpo1 + "03" + cuerpo2 + "<a target='_blank' href='" + des3_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des3_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des3_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des4'>" + cuerpo1 + "04" + cuerpo2 + "<a target='_blank' href='" + des4_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des4_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des4_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des5'>" + cuerpo1 + "05" + cuerpo2 + "<a target='_blank' href='" + des5_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des5_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des5_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des6'>" + cuerpo1 + "06" + cuerpo2 + "<a target='_blank' href='" + des6_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des6_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des6_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des7'>" + cuerpo1 + "07" + cuerpo2 + "<a target='_blank' href='" + des7_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des7_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des7_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des8'>" + cuerpo1 + "08" + cuerpo2 + "<a target='_blank' href='" + des8_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des8_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des8_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des9'>" + cuerpo1 + "09" + cuerpo2 + "<a target='_blank' href='" + des9_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des9_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des9_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des10'>" + cuerpo1 + "10" + cuerpo2 + "<a target='_blank' href='" + des10_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des10_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des10_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des11'>" + cuerpo1 + "11" + cuerpo2 + "<a target='_blank' href='" + des11_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des11_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des11_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des12'>" + cuerpo1 + "12" + cuerpo2 + "<a target='_blank' href='" + des12_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des12_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des12_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des13'>" + cuerpo1 + "13" + cuerpo2 + "<a target='_blank' href='" + des13_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des13_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des13_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des14'>" + cuerpo1 + "14" + cuerpo2 + "<a target='_blank' href='" + des14_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des14_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des14_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des15'>" + cuerpo1 + "15" + cuerpo2 + "<a target='_blank' href='" + des15_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des15_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des15_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des16'>" + cuerpo1 + "16" + cuerpo2 + "<a target='_blank' href='" + des16_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des16_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des16_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des17'>" + cuerpo1 + "17" + cuerpo2 + "<a target='_blank' href='" + des17_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des17_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des17_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des18'>" + cuerpo1 + "18" + cuerpo2 + "<a target='_blank' href='" + des18_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des18_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des18_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des19'>" + cuerpo1 + "19" + cuerpo2 + "<a target='_blank' href='" + des19_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des19_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des19_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des20'>" + cuerpo1 + "20" + cuerpo2 + "<a target='_blank' href='" + des20_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des20_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des20_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des21'>" + cuerpo1 + "21" + cuerpo2 + "<a target='_blank' href='" + des21_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des21_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des21_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des22'>" + cuerpo1 + "22" + cuerpo2 + "<a target='_blank' href='" + des22_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des22_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des22_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des23'>" + cuerpo1 + "23" + cuerpo2 + "<a target='_blank' href='" + des23_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des23_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des23_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des24'>" + cuerpo1 + "24" + cuerpo2 + "<a target='_blank' href='" + des24_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des24_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des24_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des25'>" + cuerpo1 + "25" + cuerpo2 + "<a target='_blank' href='" + des25_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des25_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des25_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des26'>" + cuerpo1 + "26" + cuerpo2 + "<a target='_blank' href='" + des26_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des26_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des26_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des27'>" + cuerpo1 + "27" + cuerpo2 + "<a target='_blank' href='" + des27_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des27_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des27_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des28'>" + cuerpo1 + "28" + cuerpo2 + "<a target='_blank' href='" + des28_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des28_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des28_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des19'>" + cuerpo1 + "29" + cuerpo2 + "<a target='_blank' href='" + des29_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des29_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des29_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des30'>" + cuerpo1 + "30" + cuerpo2 + "<a target='_blank' href='" + des30_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des30_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des30_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des31'>" + cuerpo1 + "31" + cuerpo2 + "<a target='_blank' href='" + des31_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des31_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des31_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des32'>" + cuerpo1 + "32" + cuerpo2 + "<a target='_blank' href='" + des32_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des32_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des32_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des33'>" + cuerpo1 + "33" + cuerpo2 + "<a target='_blank' href='" + des33_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des33_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des33_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des34'>" + cuerpo1 + "34" + cuerpo2 + "<a target='_blank' href='" + des34_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des34_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des34_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des35'>" + cuerpo1 + "35" + cuerpo2 + "<a target='_blank' href='" + des35_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des35_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des35_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des36'>" + cuerpo1 + "36" + cuerpo2 + "<a target='_blank' href='" + des36_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des36_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des36_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des37'>" + cuerpo1 + "37" + cuerpo2 + "<a target='_blank' href='" + des37_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des37_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des37_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des38'>" + cuerpo1 + "38" + cuerpo2 + "<a target='_blank' href='" + des38_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des38_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des38_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des39'>" + cuerpo1 + "39" + cuerpo2 + "<a target='_blank' href='" + des39_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des39_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des39_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des40'>" + cuerpo1 + "40" + cuerpo2 + "<a target='_blank' href='" + des40_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des40_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des40_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des41'>" + cuerpo1 + "41" + cuerpo2 + "<a target='_blank' href='" + des41_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des41_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des41_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des42'>" + cuerpo1 + "42" + cuerpo2 + "<a target='_blank' href='" + des42_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des42_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des42_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des43'>" + cuerpo1 + "43" + cuerpo2 + "<a target='_blank' href='" + des43_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des43_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des43_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des44'>" + cuerpo1 + "44" + cuerpo2 + "<a target='_blank' href='" + des44_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des44_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des44_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des45'>" + cuerpo1 + "45" + cuerpo2 + "<a target='_blank' href='" + des45_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des45_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des45_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des46'>" + cuerpo1 + "46" + cuerpo2 + "<a target='_blank' href='" + des46_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des46_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des46_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des47'>" + cuerpo1 + "47" + cuerpo2 + "<a target='_blank' href='" + des47_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des47_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des47_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des48'>" + cuerpo1 + "48" + cuerpo2 + "<a target='_blank' href='" + des48_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des48_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des48_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des49'>" + cuerpo1 + "49" + cuerpo2 + "<a target='_blank' href='" + des49_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des49_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des49_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des50'>" + cuerpo1 + "50" + cuerpo2 + "<a target='_blank' href='" + des50_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des50_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des50_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des51'>" + cuerpo1 + "51" + cuerpo2 + "<a target='_blank' href='" + des51_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des51_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des51_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des52'>" + cuerpo1 + "52" + cuerpo2 + "<a target='_blank' href='" + des52_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des52_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des52_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des53'>" + cuerpo1 + "53" + cuerpo2 + "<a target='_blank' href='" + des53_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des53_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des53_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des54'>" + cuerpo1 + "54" + cuerpo2 + "<a target='_blank' href='" + des54_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des54_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des54_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des55'>" + cuerpo1 + "55" + cuerpo2 + "<a target='_blank' href='" + des55_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des55_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des55_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des56'>" + cuerpo1 + "56" + cuerpo2 + "<a target='_blank' href='" + des56_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des56_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des56_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des57'>" + cuerpo1 + "57" + cuerpo2 + "<a target='_blank' href='" + des57_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des57_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des57_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des58'>" + cuerpo1 + "58" + cuerpo2 + "<a target='_blank' href='" + des58_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des58_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des58_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des59'>" + cuerpo1 + "59" + cuerpo2 + "<a target='_blank' href='" + des59_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des59_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des59_3 + "'>" + answerST + cuerpo4 +
"<tr id='redesc' class='des60'>" + cuerpo1 + "60" + cuerpo2 + "<a target='_blank' href='" + des60_1 + "'>" + answerMG + cuerpo3 + "<a target='_blank' href='" + des60_2 + "'>" + answerZS + cuerpo3 + "<a target='_blank' href='" + des60_3 + "'>" + answerST + cuerpo4;
